BEGIN TRANSACTION;
CREATE TABLE 'NPSData2' (
	'Category'	,
	'Date'	,
	'Location'	
);
INSERT INTO 'NPSData2' VALUES ('Park','March 1 1872','Wyoming');
INSERT INTO 'NPSData2' VALUES ('Park','September 25 1890','California');
INSERT INTO 'NPSData2' VALUES ('Park','October 1, 1890','California');
INSERT INTO 'NPSData2' VALUES ('Forest','March 30, 1891','Wyoming');
INSERT INTO 'NPSData2' VALUES ('Forest','June 16, 1891','Colorado');
INSERT INTO 'NPSData2' VALUES ('Forest','January 11, 1892','New Mexico');
INSERT INTO 'NPSData2' VALUES ('Forest','February 11, 1892','Colorado');
INSERT INTO 'NPSData2' VALUES ('Forest','June 17, 1892','Oregon');
INSERT INTO 'NPSData2' VALUES ('Forest','February 14, 1893','California');
INSERT INTO 'NPSData2' VALUES ('Forest','February 25, 1893','California');
INSERT INTO 'NPSData2' VALUES ('Forest','February 25, 1893','California');
INSERT INTO 'NPSData2' VALUES ('Forest','February 22, 1897','Wyoming');
INSERT INTO 'NPSData2' VALUES ('Forest','February 22, 1897','Montana');
INSERT INTO 'NPSData2' VALUES ('Forest','February 22, 1897','South Dakota');
INSERT INTO 'NPSData2' VALUES ('Forest','February 22, 1897','Wyoming');
INSERT INTO 'NPSData2' VALUES ('Forest','February 22, 1897','Montana');
INSERT INTO 'NPSData2' VALUES ('Forest','February 22, 1897','Montana');
INSERT INTO 'NPSData2' VALUES ('Forest','February 22, 1897','Washington');
INSERT INTO 'NPSData2' VALUES ('Forest','February 22, 1897','Washington');
INSERT INTO 'NPSData2' VALUES ('Forest','February 22, 1897','California');
INSERT INTO 'NPSData2' VALUES ('Forest','February 22, 1897','Utah');
INSERT INTO 'NPSData2' VALUES ('Forest','March 2, 1898','California');
INSERT INTO 'NPSData2' VALUES ('Forest','May 10, 1898','Arizona');
INSERT INTO 'NPSData2' VALUES ('Forest','August 17, 1898','Arizona');
INSERT INTO 'NPSData2' VALUES ('Forest','August 17, 1898','Arizona');
INSERT INTO 'NPSData2' VALUES ('Forest','February 10, 1899','Utah');
INSERT INTO 'NPSData2' VALUES ('Forest','February 10, 1899','Montana');
INSERT INTO 'NPSData2' VALUES ('Park','March 2, 1899','Washington');
INSERT INTO 'NPSData2' VALUES ('Forest','March 2, 1899','New Mexico');
INSERT INTO 'NPSData2' VALUES ('Forest','April 13, 1899','California');
INSERT INTO 'NPSData2' VALUES ('Forest','April 11, 1902','Arizona');
INSERT INTO 'NPSData2' VALUES ('Forest','April 11, 1902','Colorado');
INSERT INTO 'NPSData2' VALUES ('Forest','April 16, 1902','Nebraska');
INSERT INTO 'NPSData2' VALUES ('Park','May 22, 1902','Oregon');
INSERT INTO 'NPSData2' VALUES ('Forest','May 22, 1902','Colorado');
INSERT INTO 'NPSData2' VALUES ('Forest','July 26, 1902','New Mexico');
INSERT INTO 'NPSData2' VALUES ('Park','January 9, 1903','South Dakota');
INSERT INTO 'NPSData2' VALUES ('Forest','May 29, 1903','Utah');
INSERT INTO 'NPSData2' VALUES ('Forest','October 24, 1903','Colorado');
INSERT INTO 'NPSData2' VALUES ('Forest','November 29, 1904','California');
INSERT INTO 'NPSData2' VALUES ('Forest','March 27, 1905','California');
INSERT INTO 'NPSData2' VALUES ('Forest','April 26, 1905','California');
INSERT INTO 'NPSData2' VALUES ('Forest','May 6, 1905','California');
INSERT INTO 'NPSData2' VALUES ('Forest','May 6, 1905','Oregon');
INSERT INTO 'NPSData2' VALUES ('Forest','May 12, 1905','Colorado');
INSERT INTO 'NPSData2' VALUES ('Forest','May 23, 1905','Idaho');
INSERT INTO 'NPSData2' VALUES ('Forest','May 29, 1905','Idaho');
INSERT INTO 'NPSData2' VALUES ('Forest','June 2, 1905','California');
INSERT INTO 'NPSData2' VALUES ('Forest','June 3, 1905','Idaho');
INSERT INTO 'NPSData2' VALUES ('Forest','June 3, 1905','Colorado');
INSERT INTO 'NPSData2' VALUES ('Forest','June 14, 1905','Colorado');
INSERT INTO 'NPSData2' VALUES ('Forest','September 25, 1905','Utah');
INSERT INTO 'NPSData2' VALUES ('Forest','October 3, 1905','Arizona');
INSERT INTO 'NPSData2' VALUES ('Forest','April 12, 1906','Montana');
INSERT INTO 'NPSData2' VALUES ('Forest','May 3, 1906','Nevada');
INSERT INTO 'NPSData2' VALUES ('Park','June 29, 1906','Colorado');
INSERT INTO 'NPSData2' VALUES ('Forest','August 13, 1906','Montana');
INSERT INTO 'NPSData2' VALUES ('Forest','September 17, 1906','Oregon');
INSERT INTO 'NPSData2' VALUES ('Forest','September 20, 1906','Montana');
INSERT INTO 'NPSData2' VALUES ('Forest','November 6, 1906','New Mexico');
INSERT INTO 'NPSData2' VALUES ('Forest','November 6, 1906','Idaho');
INSERT INTO 'NPSData2' VALUES ('Forest','November 7, 1906','New Mexico');
INSERT INTO 'NPSData2' VALUES ('Forest','February 6, 1907','North Carolina');
INSERT INTO 'NPSData2' VALUES ('Forest','March 1, 1907','Washington');
INSERT INTO 'NPSData2' VALUES ('Forest','March 2 1907','Oregon');
INSERT INTO 'NPSData2' VALUES ('Forest','May 25, 1907','California');
INSERT INTO 'NPSData2' VALUES ('Forest','July 23, 1907','Alaska');
INSERT INTO 'NPSData2' VALUES ('Forest','September 10, 1907','Alaska');
INSERT INTO 'NPSData2' VALUES ('Forest','December 18, 1907','Arkansas');
INSERT INTO 'NPSData2' VALUES ('Forest','March 5, 1908','Arkansas');
INSERT INTO 'NPSData2' VALUES ('Forest','May 23, 1908','Minnesota');
INSERT INTO 'NPSData2' VALUES ('Forest','July 1, 1908','Utah');
INSERT INTO 'NPSData2' VALUES ('Forest','July 1, 1908','Montana');
INSERT INTO 'NPSData2' VALUES ('Forest','July 1, 1908','Idaho');
INSERT INTO 'NPSData2' VALUES ('Forest','July 1, 1908','Oregon');
INSERT INTO 'NPSData2' VALUES ('Forest','July 1, 1908','Washington');
INSERT INTO 'NPSData2' VALUES ('Forest','July 1, 1908','Colorado');
INSERT INTO 'NPSData2' VALUES ('Forest','July 1, 1908','Arizona');
INSERT INTO 'NPSData2' VALUES ('Forest','July 1, 1908','Oregon');
INSERT INTO 'NPSData2' VALUES ('Forest','July 1, 1908','California');
INSERT INTO 'NPSData2' VALUES ('Forest','July 1, 1908','Idaho');
INSERT INTO 'NPSData2' VALUES ('Forest','July 1, 1908','Colorado');
INSERT INTO 'NPSData2' VALUES ('Forest','July 1, 1908','Idaho');
INSERT INTO 'NPSData2' VALUES ('Forest','July 1, 1908','California');
INSERT INTO 'NPSData2' VALUES ('Forest','July 1, 1908','Oregon');
INSERT INTO 'NPSData2' VALUES ('Forest','July 1, 1908','Oregon');
INSERT INTO 'NPSData2' VALUES ('Forest','November 24, 1908','Florida');
INSERT INTO 'NPSData2' VALUES ('Forest','February 13, 1909','Minnesota');
INSERT INTO 'NPSData2' VALUES ('Park','May 11, 1910','Montana');
INSERT INTO 'NPSData2' VALUES ('Forest','July 28, 1910','California');
INSERT INTO 'NPSData2' VALUES ('Forest','July 1, 1911','Oregon');
INSERT INTO 'NPSData2' VALUES ('Forest','July 1, 1911','Washington');
INSERT INTO 'NPSData2' VALUES ('Monument','October 14, 1913','California');
INSERT INTO 'NPSData2' VALUES ('Park','January 26, 1915','Colorado');
INSERT INTO 'NPSData2' VALUES ('Monument','February 11, 1916','New Mexico');
INSERT INTO 'NPSData2' VALUES ('Park','August 1, 1916','Hawaii');
INSERT INTO 'NPSData2' VALUES ('Park','August 9, 1916','California');
INSERT INTO 'NPSData2' VALUES ('Monument','August 9, 1916','New Mexico');
INSERT INTO 'NPSData2' VALUES ('Forest','October 17, 1916','North Carolina');
INSERT INTO 'NPSData2' VALUES ('Park','February 26, 1917','Alaska');
INSERT INTO 'NPSData2' VALUES ('Forest','January 15, 1918','Alabama');
INSERT INTO 'NPSData2' VALUES ('Forest','May 16, 1918','Virginia');
INSERT INTO 'NPSData2' VALUES ('Forest','May 16, 1918','New Hampshire');
INSERT INTO 'NPSData2' VALUES ('Monument','August 3, 1918','Arizona');
INSERT INTO 'NPSData2' VALUES ('Park','February 26, 1919','Maine');
INSERT INTO 'NPSData2' VALUES ('Park','February 26, 1919','Arizona');
INSERT INTO 'NPSData2' VALUES ('Park','November 19, 1919','Utah');
INSERT INTO 'NPSData2' VALUES ('Forest','April 28, 1920','West Virginia');
INSERT INTO 'NPSData2' VALUES ('Forest','June 14, 1920','Tennessee');
INSERT INTO 'NPSData2' VALUES ('Park','March 4, 1921','Arkansas');
INSERT INTO 'NPSData2' VALUES ('Monument','January 24, 1923','New Mexico');
INSERT INTO 'NPSData2' VALUES ('Forest','September 24, 1923','Pennsylvania');
INSERT INTO 'NPSData2' VALUES ('Monument','April 18, 1924','Arizona');
INSERT INTO 'NPSData2' VALUES ('Monument','October 15, 1924','Florida');
INSERT INTO 'NPSData2' VALUES ('Park','May 22, 1926','Virginia');
INSERT INTO 'NPSData2' VALUES ('Park','February 25, 1928','Utah');
INSERT INTO 'NPSData2' VALUES ('Forest','July 30, 1928','Michigan');
INSERT INTO 'NPSData2' VALUES ('Park','February 26, 1929','Wyoming');
INSERT INTO 'NPSData2' VALUES ('Park','April 12, 1929','Utah');
INSERT INTO 'NPSData2' VALUES ('Park','May 14, 1930','New Mexico');
INSERT INTO 'NPSData2' VALUES ('Forest','June 10, 1930','Louisiana');
INSERT INTO 'NPSData2' VALUES ('Forest','January 16, 1931','Michigan');
INSERT INTO 'NPSData2' VALUES ('Forest','January 27, 1931','Michigan');
INSERT INTO 'NPSData2' VALUES ('Monument','April 1, 1931','Arizona');
INSERT INTO 'NPSData2' VALUES ('Forest','July 10, 1931','Florida');
INSERT INTO 'NPSData2' VALUES ('Forest','April 25, 1932','Vermont');
INSERT INTO 'NPSData2' VALUES ('Forest','March 2, 1933','Wisconsin');
INSERT INTO 'NPSData2' VALUES ('Forest','July 1, 1933','Oregon');
INSERT INTO 'NPSData2' VALUES ('Monument','August 22, 1933','Utah');
INSERT INTO 'NPSData2' VALUES ('Park','May 30, 1934','Florida');
INSERT INTO 'NPSData2' VALUES ('Park','June 15, 1934','Tennessee');
INSERT INTO 'NPSData2' VALUES ('Forest','May 13, 1936','Florida');
INSERT INTO 'NPSData2' VALUES ('Park','June 29, 1938','Washington');
INSERT INTO 'NPSData2' VALUES ('Park','March 4, 1940','California');
INSERT INTO 'NPSData2' VALUES ('Park','April 3, 1940','Michigan');
INSERT INTO 'NPSData2' VALUES ('Park','July 1, 1941','Kentucky');
INSERT INTO 'NPSData2' VALUES ('Park','June 12, 1944','Texas');
INSERT INTO 'NPSData2' VALUES ('Monument','August 12, 1946','New York');
INSERT INTO 'NPSData2' VALUES ('Seashore','January 12, 1953','North Carolina');
INSERT INTO 'NPSData2' VALUES ('Monument','April 2, 1956','Virginia');
INSERT INTO 'NPSData2' VALUES ('Park','August 2, 1956','Virgin Islands');
INSERT INTO 'NPSData2' VALUES ('Seashore','August 7, 1961','Massachusetts');
INSERT INTO 'NPSData2' VALUES ('Park','December 9, 1962','Arizona');
INSERT INTO 'NPSData2' VALUES ('Seashore','September 11, 1964','New York');
INSERT INTO 'NPSData2' VALUES ('Park','September 12, 1964','Utah');
INSERT INTO 'NPSData2' VALUES ('Monument','August 21, 1965','Texas');
INSERT INTO 'NPSData2' VALUES ('Seashore','September 21, 1965','Maryland');
INSERT INTO 'NPSData2' VALUES ('Seashore','March 10, 1966','North Carolina');
INSERT INTO 'NPSData2' VALUES ('Park','October 15, 1966','Texas');
INSERT INTO 'NPSData2' VALUES ('Seashore','April 6, 1968','Texas');
INSERT INTO 'NPSData2' VALUES ('Park','October 2, 1968','Washington');
INSERT INTO 'NPSData2' VALUES ('Park','October 2, 1968','California');
INSERT INTO 'NPSData2' VALUES ('Park','January 8, 1971','Minnesota');
INSERT INTO 'NPSData2' VALUES ('Seashore','January 8, 1971','Florida');
INSERT INTO 'NPSData2' VALUES ('Park','December 18, 1971','Utah');
INSERT INTO 'NPSData2' VALUES ('Seashore','October 20, 1972','California');
INSERT INTO 'NPSData2' VALUES ('Seashore','October 23, 1972','Georgia');
INSERT INTO 'NPSData2' VALUES ('Seashore','January 3, 1975','Florida');
INSERT INTO 'NPSData2' VALUES ('Park','November 10, 1978','South Dakota');
INSERT INTO 'NPSData2' VALUES ('Park','November 10, 1978','North Dakota');
INSERT INTO 'NPSData2' VALUES ('Monument','December 1, 1978','Alaska');
INSERT INTO 'NPSData2' VALUES ('Monument','December 1, 1978','Alaska');
INSERT INTO 'NPSData2' VALUES ('Park','March 5, 1980','California');
INSERT INTO 'NPSData2' VALUES ('Park','June 28, 1980','Florida');
INSERT INTO 'NPSData2' VALUES ('Park','December 2, 1980','Alaska');
INSERT INTO 'NPSData2' VALUES ('Park','December 2, 1980','Alaska');
INSERT INTO 'NPSData2' VALUES ('Park','December 2, 1980','Alaska');
INSERT INTO 'NPSData2' VALUES ('Park','December 2, 1980','Alaska');
INSERT INTO 'NPSData2' VALUES ('Park','December 2, 1980','Alaska');
INSERT INTO 'NPSData2' VALUES ('Park','December 2, 1980','Alaska');
INSERT INTO 'NPSData2' VALUES ('Park','December 2, 1980','Alaska');
INSERT INTO 'NPSData2' VALUES ('Park','October 27, 1986','Nevada');
INSERT INTO 'NPSData2' VALUES ('Park','October 26, 1992','Florida');
INSERT INTO 'NPSData2' VALUES ('Park','October 14, 1994','Arizona');
INSERT INTO 'NPSData2' VALUES ('Park','October 31, 1994','California');
INSERT INTO 'NPSData2' VALUES ('Park','October 31, 1994','California');
INSERT INTO 'NPSData2' VALUES ('Monument','June 14, 1997','Nebraska');
INSERT INTO 'NPSData2' VALUES ('Park','October 21, 1999','Colorado');
INSERT INTO 'NPSData2' VALUES ('Park','October 11, 2000','Ohio');
INSERT INTO 'NPSData2' VALUES ('Park','November 10, 2003','South Carolina');
INSERT INTO 'NPSData2' VALUES ('Park','September 13, 2004','Colorado');
INSERT INTO 'NPSData2' VALUES ('Monument','February 27, 2006','New York');
INSERT INTO 'NPSData2' VALUES ('Monument','October 8, 2012','California');
INSERT INTO 'NPSData2' VALUES ('Park','January 10, 2013','California');
INSERT INTO 'NPSData2' VALUES ('Monument','March 25, 2013','Ohio');
INSERT INTO 'NPSData2' VALUES ('Monument','February 12, 2016','California');
INSERT INTO 'NPSData2' VALUES ('Monument','April 12, 2016','Washington, D.C.');